version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/code

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Grant execute permission for gradlew
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - run:
          name: Run Instrumentation Tests
          command: ./gradlew connectedAndroidTest
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: debug-apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
