version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/code

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Build APK
          command: ./gradlew assembleDebug

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
