version: 2.1

orbs:
  android: circleci/android@2.4.0
  ruby: circleci/ruby@1.1.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout

      - ruby/install:
          version: 3.1.2  # Spécifiez la version Ruby requise par votre projet

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Fastlane
          command: bundle install

      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version

      - run:
          name: Assemble Debug Build
          command: ./gradlew assembleDebug

      - run:
          name: Run Fastlane Test Lane
          command: bundle exec fastlane test

  deploy:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Fastlane
          command: bundle install

      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version

      - run:
          name: Run Fastlane Deploy Lane
          command: bundle exec fastlane deploy_to_testapp

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
