version: 2.1

orbs:
  android: circleci/android@2.4.0
  fastlane: circleci/fastlane@2.2.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - run:
          name: Assemble debug build
          command: ./gradlew assembleDebug
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86
      - run:
          name: Assemble release build
          command: ./gradlew clean assembleRelease
      - run:
          name: List APK directory contents
          command: ls -l app/build/outputs/apk/release/
      - run:
          name: Install Bundler
          command: bundle install
      - fastlane/run:
          name: Run Fastlane Deploy
          lane: deploy_to_testapp

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
