version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout

      # Installer OpenJDK 17
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version

      # Créer et démarrer un AVD
      - run:
          name: Create and Start Emulator
          command: |
            echo "Creating and starting emulator..."
            echo "no" | sdkmanager --sdk_root=/usr/local/android-sdk --install "system-images;android-30;google_apis;x86"
            echo "no" | avdmanager create avd --name Pixel_4_XL_API_30 --package "system-images;android-30;google_apis;x86" --device "pixel_4_xl" --sdcard 512M
            emulator -avd Pixel_6_PRO_API_30 -no-audio -no-boot-anim &
            adb wait-for-device
            adb shell input keyevent 82
            echo "Emulator started."

      # Attendre que l'émulateur soit prêt
      - run:
          name: Wait for Emulator
          command: |
            echo "Waiting for emulator to boot..."
            while [[ $(adb shell getprop sys.boot_completed 2>/dev/null) != 1 ]]; do
              sleep 5
            done
            echo "Emulator is ready!"

      # Installer Bundler
      - run:
          name: Install Bundler
          command: gem install bundler

      # Installer les gems
      - run:
          name: Bundle Install
          command: bundle install

      # Exécuter Fastlane pour construire les APKs et capturer les écrans
      - run:
          name: Run Fastlane Deploy
          command: bundle exec fastlane test_and_deploy

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
