version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/code

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install prerequisites
          command: sudo apt-get update && sudo apt-get install -y software-properties-common
      - run:
          name: Add PPA for OpenJDK 17
          command: |
            sudo add-apt-repository ppa:openjdk-r/ppa
            sudo apt-get update
      - run:
          name: Install Java 17
          command: |
            sudo apt-get install -y openjdk-17-jdk
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verify Java Version
          command: java -version
      - run:
          name: Grant execute permission for gradlew
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - run:
          name: Run Instrumentation Tests
          command: ./gradlew connectedAndroidTest
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: debug-apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
