fastlane_version "2.221.1"  # Spécifie la version de Fastlane, ajuste selon tes besoins

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build and deploy to TestApp.io"
  lane :deploy_to_testapp do
   upload_to_testappio(
       api_token: ENV['TESTAPPIO_API_TOKEN'],
       app_id: ENV['TESTAPPIO_APP_ID'],
       release: "android",
       apk_file: ENV['APK_PATH'],
       release_notes: "Manual release notes for Android",
       git_release_notes: true,
       git_commit_id: false,
       notify: false
     )
    end

    desc "Run tests and deploy"
      lane :test_and_deploy do
        test
        deploy_to_testapp
      end

end
