default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build and deploy to TestApp.io"
  lane :deploy_to_testapp do
    # Nettoyer et assembler le build
    gradle(task: "clean assembleRelease")

    apk_path = "app/build/outputs/apk/release/app-release-unsigned.apk"

        # Envoyer le fichier APK à TestApp.io via une requête HTTP POST
        sh "curl -X POST https://api.testapp.io/deploy \
            -H 'Authorization: Bearer #{ENV['TESTAPPIO_API_TOKEN']}' \
            -F 'file=@#{apk_path}' \
            -F 'version=1.0.0' \
            -F 'notes=Initial release' \
            -F 'app_id=#{ENV['TESTAPPIO_APP_ID']}'"
  end
end
