default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build and deploy to TestApp.io"
  lane :deploy_to_testapp do
    apk_path = "app/build/outputs/apk/release/app-release-unsigned.apk"
    if File.exist?(apk_path)
      sh "curl -X POST https://api.testapp.io/deploy \
        -H 'Authorization: Bearer #{ENV['TESTAPPIO_API_TOKEN']}' \
        -F 'file=@#{Dir.pwd}/#{apk_path}' \
        -F 'version=1.0.0' \
        -F 'notes=Initial release' \
        -F 'app_id=**********'"
    else
      UI.user_error!("APK file not found at path: #{apk_path}")
    end
  end

end
